### ISSUE TITLE
can you share the dataset for change detection

### ISSUE THREAD

**Issue by ARnnn** [Hhhhhhhhhhao/change_detection#1]
can you share the dataset for change detection

**Comment by ARnnn** [comment]
1:When I read the metrics.py ,I get two mean_iou(),which is right, please? 
2:I found this data set, but it's a four-channel one. Did you take three of them to do it?

**Comment by ARnnn** [comment]
How many pictures did you use in training?

**Comment by Hhhhhhao** [comment]
@ARnnn Hi, sorry for the delayed response.
The dataset I used is a change detection dataset from here: http://rscup.bjxintong.com.cn/.
The second mean_iou function is better.
For the dataset I used 4 channels directly as input.

**Comment by ARnnn** [comment]
thanks for you reply.ang in addition ,in your test.py file, where are val_img_paths, val_mask_paths defined, and where are the test data to be passed in?

**Comment by ARnnn** [comment]
thanks for you reply.ang in addition ,in your test.py file, where are val_img_paths, val_mask_paths defined, and where are the test data to be passed in?the most important is that how can i run the test.py

**Comment by ARnnn** [comment]
thanks for you reply.ang in addition ,in your test.py file, where are val_img_paths, val_mask_paths defined, and where are the test data to be passed in?the most important is that how can i run the test.py

**Comment by ARnnn** [comment]
thanks for you reply.ang in addition ,in your test.py file, where are val_img_paths, val_mask_paths defined, and where are the test data to be passed in?the most important is that how can i run the test.py

**Comment by Hhhhhhao** [comment]
@ARnnn The dataset.py file directly read the data, so long as you are putting the data under the data folder.

**Comment by ARnnn** [comment]
but when i run the test.py ,i got the error:
   => creating model NestedUNet
Traceback (most recent call last):
  File "test.py", line 104, in <module>
    main()
  File "test.py", line 48, in main
    model = models.__dict__[args.arch](args)
  File "I:\change_detection-master\change_detection-master\models.py", line 71, in __init__
    self.conv0_0 = ResBlock(in_ch, filters[0])
  File "I:\change_detection-master\change_detection-master\models.py", line 43, in __init__
    self.conv1 = nn.Conv2d(in_channels=in_ch, out_channels=out_ch, kernel_size=3, stride=stride, padding=1, dilation=1, bias=True)
  File "D:\Anaconda3\lib\site-packages\torch\nn\modules\conv.py", line 327, in __init__
    False, _pair(0), groups, bias, padding_mode)
  File "D:\Anaconda3\lib\site-packages\torch\nn\modules\conv.py", line 21, in __init__
    if in_channels % groups != 0:
TypeError: unsupported operand type(s) for %: 'Namespace' and 'int'

how can i solve it

**Comment by Hhhhhhao** [comment]
@ARnnn  I think there is a bug 

line 48 should read arg.channels into model rather than arg.
I fixed it.

**Comment by GH-W5** [comment]
> 1：当我读取metrics.py时，我得到两个mean_iou（），对吗？
> 2：我找到了这个数据集，但这是一个四通道数据集。您是否接受了其中的三个？

Can you share the dataset?

**Comment by ARnnn** [comment]
in test.py,what do val_img_paths and val_mask_paths represent and where are they defined?

**Comment by Hhhhhhao** [comment]
the dataset can be download from here: http://rscup.bjxintong.com.cn/#/theme/4

the val_ima_paths and mask_paths are defined in dataset.py

**Comment by ARnnn** [comment]
I'm talking about val_img_paths on line 71 and val_mask_paths on line 80 in test.py. As you know, I didn't find them in dataset.py. Can you tell me the number of rows in dataset.py?

**Comment by ARnnn** [comment]
My problem now is that when I run test.py, the following errors occur:

Traceback (most recent call last):
  File "test.py", line 107, in <module>
    main()
  File "test.py", line 80, in main
    for i in tqdm(range(len(val_mask_paths))):
NameError: name 'val_mask_paths' is not defined



how can i solve it?

**Comment by wghvip** [comment]
兄弟没有数据集，不知怎么帮你，那个网站不能注册了，你能分享一下数据集吗

**Comment by ARnnn** [comment]
> 兄弟没有数据集，不知怎么帮你，那个网站不能注册了，你能分享一下数据集吗

加个联系方式吧，这个数据集赛方好像不让一直外传

**Comment by wghvip** [comment]
发我一份数据集，一起探讨可以吗 1961879865@qq.com @ARnnn

**Comment by wghvip** [comment]
@ARnnn @ARnnn 跪求数据，

**Comment by ARnnn** [comment]
I think that 79 to 99 lines of code in test. py are an evaluation criterion, so comment it out. ThenI run test.py, the following errors occur:

Traceback (most recent call last):
  File "test.py", line 116, in <module>
    main()
  File "test.py", line 73, in main
    for i, (input, target) in tqdm(enumerate(val_loader), total=len(val_loader))
:
  File "D:\Anaconda3\lib\site-packages\tqdm\_tqdm.py", line 1005, in __iter__
    for obj in iterable:
  File "D:\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 346
, in __next__
    data = self.dataset_fetcher.fetch(index)  # may raise StopIteration
  File "D:\Anaconda3\lib\site-packages\torch\utils\data\_utils\fetch.py", line 4
7, in fetch
    return self.collate_fn(data)
  File "E:\z\change_detection-master\change_detection-master\data_loaders.py", l
ine 11, in collate_fn
    img, mask = data[0]
ValueError: too many values to unpack (expected 2)

how can i solve it?

**Comment by ARnnn** [comment]
Is the data you used to test a test set of 83 pictures provided by the competitors?

**Comment by ARnnn** [comment]
How do you make 256 * 256 pictures for training? How many pictures are used for training

**Comment by ARnnn** [comment]
Why is the test result all black after I run with your code?

**Comment by Hhhhhhao** [comment]
@ARnnn maybe you have too much black pixels in your ground truth than the white pixels. Have you checked the detection masks generated during training?

**Comment by ARnnn** [comment]
> @ARnnn maybe you have too much black pixels in your ground truth than the white pixels. Have you checked the detection masks generated during training?

I cut the original image into 256 small pieces to train, and ensure that every training set has white pixels, but after training, the test model is all black. Can you upload your training set and model?

**Comment by Hhhhhhao** [comment]
> > @ARnnn maybe you have too much black pixels in your ground truth than the white pixels. Have you checked the detection masks generated during training?
> 
> I cut the original image into 256 small pieces to train, and ensure that every training set has white pixels, but after training, the test model is all black. Can you upload your training set and model?

sorry I didn;t have the data and model any more

**Comment by ARnnn** [comment]
> > > @ARnnn maybe you have too much black pixels in your ground truth than the white pixels. Have you checked the detection masks generated during training?
> > 
> > 
> > I cut the original image into 256 small pieces to train, and ensure that every training set has white pixels, but after training, the test model is all black. Can you upload your training set and model?
> 
> sorry I didn;t have the data and model any more

I can give you the original training set. Can you train again? esteem it a favor!

**Comment by ARnnn** [comment]
> > > > @ARnnn maybe you have too much black pixels in your ground truth than the white pixels. Have you checked the detection masks generated during training?
> > > 
> > > 
> > > I cut the original image into 256 small pieces to train, and ensure that every training set has white pixels, but after training, the test model is all black. Can you upload your training set and model?
> > 
> > 
> > sorry I didn;t have the data and model any more
> 
> I can give you the original training set. Can you train again? esteem it a favor!

I really want to reproduce this code.

**Comment by Hhhhhhao** [comment]
> > > > > @ARnnn maybe you have too much black pixels in your ground truth than the white pixels. Have you checked the detection masks generated during training?
> > > > 
> > > > 
> > > > I cut the original image into 256 small pieces to train, and ensure that every training set has white pixels, but after training, the test model is all black. Can you upload your training set and model?
> > > 
> > > 
> > > sorry I didn;t have the data and model any more
> > 
> > 
> > I can give you the original training set. Can you train again? esteem it a favor!
> 
> I really want to reproduce this code.

really want to help but don't have GPU currently

**Comment by ARnnn** [comment]
> > > > > > @ARnnn maybe you have too much black pixels in your ground truth than the white pixels. Have you checked the detection masks generated during training?
> > > > > 
> > > > > 
> > > > > I cut the original image into 256 small pieces to train, and ensure that every training set has white pixels, but after training, the test model is all black. Can you upload your training set and model?
> > > > 
> > > > 
> > > > sorry I didn;t have the data and model any more
> > > 
> > > 
> > > I can give you the original training set. Can you train again? esteem it a favor!
> > 
> > 
> > I really want to reproduce this code.
> 
> really want to help but don't have GPU currently

Can you tell me how you organized the original training data into 256 sizes in the early stage? What are the details? In addition, what was your operating environment at that time?

**Comment by deimsdeutsch** [comment]
Unable to download dataset ... can you share baidu or google drive links ?

**Comment by Rikaaaaaa95** [comment]
> > > > > > > @ARnnn maybe you have too much black pixels in your ground truth than the white pixels. Have you checked the detection masks generated during training?
> > > > > > 
> > > > > > 
> > > > > > I cut the original image into 256 small pieces to train, and ensure that every training set has white pixels, but after training, the test model is all black. Can you upload your training set and model?
> > > > > 
> > > > > 
> > > > > sorry I didn;t have the data and model any more
> > > > 
> > > > 
> > > > I can give you the original training set. Can you train again? esteem it a favor!
> > > 
> > > 
> > > I really want to reproduce this code.
> > 
> > 
> > really want to help but don't have GPU currently
> 
> Can you tell me how you organized the original training data into 256 sizes in the early stage? What are the details? In addition, what was your operating environment at that time?

可以留一下qq么，在很多change detection下看到你

**Comment by Hhhhhhao** [comment]
留下邮箱吧 把QQ发你

**Comment by Rikaaaaaa95** [comment]
> 留下邮箱吧 把QQ发你
> […](#)
> On Jan 23, 2020, at 09:02, Rikaaaaaa95 ***@***.***> wrote: ﻿ @ARnnn maybe you have too much black pixels in your ground truth than the white pixels. Have you checked the detection masks generated during training? I cut the original image into 256 small pieces to train, and ensure that every training set has white pixels, but after training, the test model is all black. Can you upload your training set and model? sorry I didn;t have the data and model any more I can give you the original training set. Can you train again? esteem it a favor! I really want to reproduce this code. really want to help but don't have GPU currently Can you tell me how you organized the original training data into 256 sizes in the early stage? What are the details? In addition, what was your operating environment at that time? 可以留一下qq么，在很多change detection下看到你 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

690954421@qq.com

**Comment by Rikaaaaaa95** [comment]
> Unable to download dataset ... can you share baidu or google drive links ?

你好，能留下联系方式么，我也没下载好数据集

**Comment by Rikaaaaaa95** [comment]
> can you share the dataset for change detection

请问你的qq是多少？
